#!/usr/bin/groovy

/**
 this section of the pipeline executes on the master, which has a lot of useful variables that we can leverage to configure our pipeline
 **/
node (''){
    // these should align to the projects in the Application Inventory
    env.OPENSHIFT_BUILD_NAMESPACE = "infographic-pipeline"
    env.DEV_PROJECT = "infographic-dev"
    env.TEST_PROJECT = "infographic-test"
    env.UAT_PROJECT = "infographic-uat"

    // this value should be set to the root directory of your source code within the git repository.
    // if the root of the source is the root of the repo, leave this value as ""

    env.APP_NAME = "httpd-app"

    // these are defaults that will help run openshift automation
    env.OCP_API_SERVER = "${env.OPENSHIFT_API_URL}"
    env.OCP_TOKEN = readFile('/var/run/secrets/kubernetes.io/serviceaccount/token').trim()
}


/**
 this section of the pipeline executes on a custom mvn build slave.
 you should not need to change anything below unless you need new stages or new integrations (e.g. Cucumber Reports or Sonar)
 **/
node('nodejs') {

    stage('SCM Checkout') {
        checkout scm
    }

    // assumes uber jar is created
    stage('Build Image') {
        sh "echo 'apiURL: ${env.OCP_API_SERVER}'"
        sh "echo 'authToken: ${env.OCP_TOKEN}'"
        sh "echo 'destStream: ${env.APP_NAME}'"
        sh "echo 'destinationAuthToken: ${env.OCP_TOKEN}'"
        sh "echo 'destinationNamespace: ${env.DEV_PROJECT}'"
        sh "echo 'namespace: ${env.OPENSHIFT_BUILD_NAMESPACE}'"
        sh "echo 'srcStream: ${env.APP_NAME}'"
        sh "pwd"
        sh "oc start-build ${env.APP_NAME} --from-dir=website --follow"
    }


    // no user changes should be needed below this point
    stage ('Deploy to Dev') {
        input "Promote Application to Dev?"

        openshiftTag (apiURL: "${env.OCP_API_SERVER}", authToken: "${env.OCP_TOKEN}", destStream: "${env.APP_NAME}", destTag: 'latest', destinationAuthToken: "${env.OCP_TOKEN}", destinationNamespace: "${env.DEV_PROJECT}", namespace: "${env.OPENSHIFT_BUILD_NAMESPACE}", srcStream: "${env.APP_NAME}", srcTag: 'latest')

        openshiftVerifyDeployment (apiURL: "${env.OCP_API_SERVER}", authToken: "${env.OCP_TOKEN}", depCfg: "${env.APP_NAME}", namespace: "${env.DEV_PROJECT}", verifyReplicaCount: true)
    }

    stage ('Deploy to Test') {
        input "Promote Application to Test?"

        openshiftTag (apiURL: "${env.OCP_API_SERVER}", authToken: "${env.OCP_TOKEN}", destStream: "${env.APP_NAME}", destTag: 'latest', destinationAuthToken: "${env.OCP_TOKEN}", destinationNamespace: "${env.TEST_PROJECT}", namespace: "${env.DEV_PROJECT}", srcStream: "${env.APP_NAME}", srcTag: 'latest')

        openshiftVerifyDeployment (apiURL: "${env.OCP_API_SERVER}", authToken: "${env.OCP_TOKEN}", depCfg: "${env.APP_NAME}", namespace: "${env.TEST_PROJECT}", verifyReplicaCount: true)
    }

    stage ('Deploy to UAT') {
        input "Promote Application to UAT?"

        openshiftTag (apiURL: "${env.OCP_API_SERVER}", authToken: "${env.OCP_TOKEN}", destStream: "${env.APP_NAME}", destTag: 'latest', destinationAuthToken: "${env.OCP_TOKEN}", destinationNamespace: "${env.UAT_PROJECT}", namespace: "${env.TEST_PROJECT}", srcStream: "${env.APP_NAME}", srcTag: 'latest')

        openshiftVerifyDeployment (apiURL: "${env.OCP_API_SERVER}", authToken: "${env.OCP_TOKEN}", depCfg: "${env.APP_NAME}", namespace: "${env.UAT_PROJECT}", verifyReplicaCount: true)
    }

}